version: "3.9"

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./api:/qiita-kenny/
      - bundle:/usr/local/bundle
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' "
    ports:
      - "3001:3000"
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    command: sh -c "cd app && npm run dev"
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password && mysqld --innodb_use_native_aio=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    security_opt:
      - seccomp:unconfined
    volumes:
      - db:/var/lib/mysql
    ports:
      - "4306:3306"

volumes:
  db:
    driver: local
  bundle:
    driver: local
